### ISSUE TITLE
TypeError during auth

### ISSUE THREAD

**Issue by parras** [BoscoDomingo/SpotifyMatcher#3]
In version 1.1, I get the following error whenever I try to run the script:
```
Traceback (most recent call last):
  File "/home/parras/Téléchargements/SpotifyMatcher/./main.py", line 134, in <module>
    if auth_manager.is_token_expired(token_info):
  File "/home/parras/.local/bin/SpotifyMatcher/lib/python3.9/site-packages/spotipy/oauth2.py", line 332, in is_token_expired
    return is_token_expired(token_info)
  File "/home/parras/.local/bin/SpotifyMatcher/lib/python3.9/site-packages/spotipy/oauth2.py", line 66, in is_token_expired
    return token_info["expires_at"] - now < 60
TypeError: 'NoneType' object is not subscriptable
```
The previous version (f91bf127cb9f653d1953495e434c429af9d5a763) works fine.

**Comment by BoscoDomingo** [comment]
Interesting... It looks as though it didn't get your token despite reaching the part where it checks if said token is expired, which always happens after a succesful authentication.

I added a fix, you can implement it yourself or just pull or download the new version I'll release right now. Let me know if it works

**Comment by parras** [comment]
I confirm that 9eda9de5b79925288b39ecb29e1d966bca7835f4 fixed it. Thank you!
